package snapshotter

import (
	"encoding/json"
	"errors"
	"flag"
	"image"
	"image/png"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"

	"github.com/kylelemons/godebug/pretty"
	"github.com/pmezard/go-difflib/difflib"
)

type T interface {
	Name() string
	Error(args ...interface{})
	Errorf(format string, args ...interface{})
	Helper()
}

var rewriteFlag = flag.Bool("rewriteSnapshots", false, "Rewrite test data output. Should not be used with -rewriteWithFailOnDiff")
var rewriteWithFailOnDiff = flag.Bool("rewriteWithFailOnDiff", false, "Rewrites the snapshot while still failing the test on diff. Should not be used with -rewriteSnapshots")

func isRewrite() bool {
	rewriteEnvVar := os.Getenv("REWRITE_SNAPSHOTS") == "1"
	return rewriteEnvVar || *rewriteFlag
}

func isRewriteWithFailOnDiff() bool {
	rewriteEnvVar := os.Getenv("REWRITE_WITH_FAIL_ON_DIFF") == "1"
	return rewriteEnvVar || *rewriteWithFailOnDiff
}

type SnapshotMode int

type RenderFn func(values []interface{}) (image.Image, error)

const (
	SnapshotModeUndefined SnapshotMode = iota
	// SnapshotModeCheck means a snapshot diff will fail the test, and the
	// snapshot will not be updated.
	SnapshotModeCheck
	// SnapshotModeRewrite means a snapshot diff will be ignored, and the snapshot
	// will be rewritten.
	SnapshotModeRewrite
	// SnapshotModeCheckAndRewrite means a snapshot diff will fail the test, and
	// the snapshot will be updated.
	SnapshotModeCheckAndRewrite
)

// GlobalSnapshotMode returns the snapshot mode configured in global state
// via environment variables and/or command-line arguments.
func GlobalSnapshotMode() (SnapshotMode, error) {
	if isRewrite() && isRewriteWithFailOnDiff() {
		return SnapshotModeUndefined, errors.New("choose one of rewriteWithFailOnDiff and rewriteSnapshots, otherwise unexpected behavior can occur.")
	}

	if isRewrite() {
		return SnapshotModeRewrite, nil
	}

	if isRewriteWithFailOnDiff() {
		return SnapshotModeCheckAndRewrite, nil
	}

	return SnapshotModeCheck, nil
}

func sanitizeForPath(name string) string {
	return strings.ReplaceAll(strings.ReplaceAll(name, "/", "-"), ":", "-")
}

func jsonRoundTrip(value interface{}) (interface{}, error) {
	bytes, err := json.Marshal(value)
	if err != nil {
		return nil, err
	}
	var roundtripped interface{}
	if err := json.Unmarshal(bytes, &roundtripped); err != nil {
		return nil, err
	}
	return roundtripped, nil
}

type snapshot struct {
	Name   string
	Values []interface{}
}

// Snapshotter is a utility for writing snapshot tests. In a snapshot, the
// expected test output is generated by running the test and storing the
// output, which for complex test outputs would otherwise require a lot of
// effort to write.
type Snapshotter struct {
	t              T
	name           string
	snapshots      []*snapshot
	SnapshotErrors bool
}

// New creates a new Snapshotter. Any errors encountered will fail
// the test.
func New(t T) *Snapshotter {
	return &Snapshotter{t: t}
}

func NewNamed(t T, name string) *Snapshotter {
	return &Snapshotter{t: t, name: name}
}

// Snapshot records a value for a snapshot test. For the test to pass, all
// invocations to Snapshot should have the same arguments. All values should be
// JSON-marshalable.
func (s *Snapshotter) Snapshot(name string, values ...interface{}) {
	for i, value := range values {
		roundtripped, err := jsonRoundTrip(value)
		if err != nil {
			s.t.Errorf("%s: error roundtripping value %v: %s", name, value, err)
			return
		}
		values[i] = roundtripped
	}

	s.snapshots = append(s.snapshots, &snapshot{
		Name:   name,
		Values: values,
	})
}

func (s *Snapshotter) rewrite(name string) {
	// If there are no snapshots, then when rewriting, we want to remove the file if it exists.
	if len(s.snapshots) == 0 {
		if _, err := os.Stat(name); os.IsNotExist(err) {
			return
		}

		// The file exists, so let's remove it.
		if err := os.Remove(name); err != nil {
			s.t.Errorf("failed to remove the existing snapshot file %s", name)
		}
		return
	}
	if err := os.MkdirAll("testdata", 0755); err != nil {
		s.t.Errorf("error creating testdata directory: %s", err)
		return
	}
	bytes, err := json.MarshalIndent(s.snapshots, "", "  ")
	if err != nil {
		s.t.Errorf("error marshaling snapshots: %s", err)
		return
	}
	if err := ioutil.WriteFile(name, bytes, 0644); err != nil {
		s.t.Errorf("error writing snapshots: %s", err)
		return
	}
}

// Returns the name of the snapshot file that will/would be created when running Verify.
// Includes the testdata/ path
func (s *Snapshotter) SnapshotFileName() string {
	s.t.Helper()
	nameSuffix := ""
	if s.name != "" {
		nameSuffix = "_" + sanitizeForPath(s.name)
	}
	return filepath.Join("testdata", sanitizeForPath(s.t.Name())+nameSuffix+".snapshots.json")
}

// Verify finishes a snapshot test. It either compares the test output, or it
// rewrites the test output.
func (s *Snapshotter) Verify() {
	s.t.Helper()
	mode, err := GlobalSnapshotMode()
	if err != nil {
		s.t.Error(err)
		return
	}
	name := s.SnapshotFileName()
	if mode == SnapshotModeRewrite {
		s.rewrite(name)
	} else {
		// When no snapshots file exists and no snapshots have been taken, do nothing.
		if _, err := os.Stat(name); os.IsNotExist(err) && len(s.snapshots) == 0 {
			return
		}

		bytes, err := ioutil.ReadFile(name)
		if err != nil {
			s.t.Errorf("error reading snapshots: %s", err)
			return
		}
		var expected []*snapshot
		if err := json.Unmarshal(bytes, &expected); err != nil {
			s.t.Errorf("error unmarshaling snapshots: %s", err)
			return
		}

		if mode == SnapshotModeCheckAndRewrite {
			s.rewrite(name)
		}

		actual := s.snapshots

		var actualNames, expectedNames []string
		for _, snapshot := range actual {
			actualNames = append(actualNames, snapshot.Name)
		}
		for _, snapshot := range expected {
			expectedNames = append(expectedNames, snapshot.Name)
		}

		if diff := diffString(expectedNames, actualNames); diff != "" {
			s.t.Errorf("snapshot names differ:\n%s", diff)
			return
		}

		for i := range actual {
			expectedValue := expected[i].Values
			actualValue := actual[i].Values

			if len(expectedValue) == 1 && len(actualValue) == 1 {
				if expectedString, ok := expectedValue[0].(string); ok {
					if actualString, ok := actualValue[0].(string); ok {
						if diff := diffString(expectedString, actualString); diff != "" {
							s.t.Errorf("snapshot %s differs:\n%s", actual[i].Name, diff)
							s.t.Errorf("If this is intentional, you can run `go test . -rewriteSnapshots` to generate new snapshots.")
							return
						}
					}
				}
			}

			if diff := diffString(expected[i].Values, actual[i].Values); diff != "" {
				s.t.Errorf("snapshot %s differs:\n%s", actual[i].Name, diff)
				s.t.Errorf("If this is intentional, you can run `go test . -rewriteSnapshots` to generate new snapshots.")
			}
		}
	}
}

// VerifyWithImage calls Verify and, when rewriting snapshots, renders PNG
// images for each snapshot using the provided renderFn. Images are written to a
// sub-directory derived from the snapshot file name.
func (s *Snapshotter) VerifyWithImage(renderFn RenderFn) {
	s.t.Helper()
	s.Verify()

	mode, err := GlobalSnapshotMode()
	if err != nil {
		return
	}

	if mode != SnapshotModeRewrite && mode != SnapshotModeCheckAndRewrite {
		return
	}

	dir := strings.TrimSuffix(s.SnapshotFileName(), ".snapshots.json")
	if err := os.RemoveAll(dir); err != nil {
		s.t.Errorf("failed to remove image directory %s: %s", dir, err)
		return
	}

	if len(s.snapshots) == 0 {
		return
	}

	if err := os.MkdirAll(dir, 0755); err != nil {
		s.t.Errorf("error creating image directory %s: %s", dir, err)
		return
	}

	for _, snap := range s.snapshots {
		sanitizedName := sanitizeForPath(snap.Name)
		pngPath := filepath.Join(dir, sanitizedName+".png")

		img, err := renderFn(snap.Values)
		if err != nil {
			s.t.Errorf("error rendering image for snapshot %s: %s", snap.Name, err)
			continue
		}

		f, err := os.Create(pngPath)
		if err != nil {
			s.t.Errorf("error creating PNG file %s: %s", pngPath, err)
			continue
		}

		if err := png.Encode(f, img); err != nil {
			f.Close()
			s.t.Errorf("error encoding PNG for snapshot %s: %s", snap.Name, err)
			continue
		}

		f.Close()
	}
}

func coerceToString(i interface{}) string {
	if str, ok := i.(string); ok {
		return str
	}
	return pretty.Sprint(i)
}

func diffString(a, b interface{}) string {
	str, _ := difflib.GetUnifiedDiffString(difflib.UnifiedDiff{
		A:        difflib.SplitLines(coerceToString(a)),
		B:        difflib.SplitLines(coerceToString(b)),
		FromFile: "expected",
		ToFile:   "received",
		Context:  1,
	})

	return str
}
